# Load-balancer for SGW
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-enketo
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    org.getodk.instance: {{ .Release.Name }}-enketo
  ports:
  - targetPort: 8005
    port: 8005
    name: enketo
  type: {{ .Values.serviceType }}
