{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-enketo
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - host: {{ .Values.general.externalDomain }}
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}-odk-web
          servicePort: http
{{- end -}}
