# Load-balancer for SGW
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-odk-web
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    org.getodk.web.instance: {{ .Release.Name }}-odk-web
  ports:
  - targetPort: 80
    port: 80
    name: http
  - targetPort: 443
    port: 443
    name: https
  type: {{ .Values.serviceType }}
