apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx
  namespace: {{ .Release.Namespace }}
data:
  # TODO: support https at nginx level
  # in general we'd expect it to be managed at k8s ingress level, so for now we only support http
  nginx.conf: |
    server {
      listen 80;
      client_max_body_size 100m;

      gzip on;
      gzip_vary on;
      gzip_min_length 1280;
      gzip_http_version 1.1;
      gzip_types text/plain text/css application/json application/x-javascript text/xml text/csv;

      # Route to enketo
      # TODO: implement this at ingress level?
      location /- {
        proxy_pass http://{{ .Release.Name }}-enketo:8005/-;
        proxy_redirect off;
        proxy_set_header Host $host;
      }

      # Route to API
      # TODO: implement this at ingress level?
      location ~ ^/v\d {
        proxy_set_header X-Forwarded-Proto https;
        proxy_pass http://{{ .Release.Name }}-odk:8383;
        proxy_redirect off;

        # set up request-body gzip decompression:
        set $max_chunk_size 16384;    # ~16KB
        set $max_body_size 134217728; # ~128MB
        rewrite_by_lua_file inflate_body.lua;

        # buffer requests, but not responses, so streaming out works.
        proxy_request_buffering on;
        proxy_buffering off;
        proxy_read_timeout 2m;
      }

      location / {
        root /usr/share/nginx/html;
      }
    }
