# Sync Gateway configmap
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-odk-central
  namespace: {{ .Release.Namespace }}
stringData:
  local.json: |
    {{ include "conf_odk" . | nindent 4 }}
