kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-odk
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    org.getodk.instance: {{ .Release.Name }}-odk
  ports:
  - targetPort: 8383
    port: 8383
    name: central
  type: {{ .Values.serviceType }}
