# PVC for mariadb and nextcloud disk
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-odk
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  {{- if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.general.storageSize }}
