apiVersion: v1
kind: ConfigMap
metadata:
  name: odk-postgres-init
  namespace: {{ .Release.Namespace }}
data:
  init.sql: |
    CREATE DATABASE "{{ .Values.postgresql.dbName }}" OWNER "{{ .Values.postgresql.postgresqlUsername }}";
    \c "{{ .Values.postgresql.kpiDatabase }}"
    CREATE EXTENSION IF NOT EXISTS CITEXT;
    CREATE EXTENSION IF NOT EXISTS pg_trgm;
